-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aviones
(
    numero integer,
    modelo text COLLATE pg_catalog."default",
    peso text COLLATE pg_catalog."default",
    capacidad text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.hangares
(
    numero_hangar integer,
    capacidad text COLLATE pg_catalog."default",
    localizacion text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.piloto
(
    numero_licencia integer,
    restricciones text COLLATE pg_catalog."default",
    salario text COLLATE pg_catalog."default",
    turno text COLLATE pg_catalog."default"
);
END;